# Generated by Django 5.0.1 on 2024-11-22 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senwin_title', models.CharField(blank=True, max_length=255, null=True)),
                ('senwin_description', models.TextField()),
                ('senwin_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('senwin_image', models.ImageField(upload_to='images_sen/')),
                ('senwin_publish_date', models.DateTimeField(auto_now_add=True)),
                ('senwin_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-senwin_publish_date'],
            },
        ),
    ]
