# Generated by Django 5.0.1 on 2024-11-22 09:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senwin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainPost',
            new_name='SenwinMainPost',
        ),
    ]
