# Generated by Django 5.0.1 on 2024-11-22 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senwin', '0002_rename_mainpost_senwinmainpost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SenwinProjectPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senwin_project_title', models.CharField(blank=True, max_length=255, null=True)),
                ('senwin_project_description', models.TextField()),
                ('senwin_project_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('senwin_project_image', models.ImageField(upload_to='images_project/')),
                ('senwin_project_publish_date', models.DateTimeField(auto_now_add=True)),
                ('senwin_project_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-senwin_project_publish_date'],
            },
        ),
    ]
