# Generated by Django 5.0.1 on 2024-12-08 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senwin', '0004_contactvideo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SenwinLatestPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_post_title', models.CharField(blank=True, max_length=255, null=True)),
                ('latest_post_description', models.TextField()),
                ('latest_post_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('latest_post_image', models.ImageField(upload_to=' latest_post/')),
                ('latest_post_publish_date', models.DateTimeField(auto_now_add=True)),
                ('latest_post_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-latest_post_publish_date'],
            },
        ),
    ]
