# Generated by Django 5.1.4 on 2025-01-08 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senwin', '0005_senwinlatestpost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(blank=True, max_length=255, null=True)),
                ('category_description', models.TextField()),
                ('category_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('category_image', models.ImageField(upload_to='images_ category/')),
                ('category_publish_date', models.DateTimeField(auto_now_add=True)),
                ('category_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-category_publish_date'],
            },
        ),
        migrations.CreateModel(
            name='SecondCategoryPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_category_title', models.CharField(blank=True, max_length=255, null=True)),
                ('second_category_description', models.TextField()),
                ('second_category_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('second_category_image', models.ImageField(upload_to='images_ second_category/')),
                ('second_category_publish_date', models.DateTimeField(auto_now_add=True)),
                ('second_category_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-second_category_publish_date'],
            },
        ),
    ]
